In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
df = pd.read_csv("Resources/complete_merged_df.csv")
df

,Unnamed: 0,pha,h,e,a,q,i,om,w,ma,...,v_inf,h_cad,class_AMO,class_APO,class_ATE,class_ETc,class_HTC,class_IEO,class_JFC,class_JFc
0,0,0,0.00,0.9720,17.0700,0.479,19.33,311.59,129.61,0.27,...,31.184313,0.000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1,0,0.00,0.8192,4.3360,0.784,9.17,36.11,337.86,14.34,...,15.663247,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2,0,0.00,0.8483,2.2150,0.336,11.78,334.57,186.55,202.74,...,31.636268,0.000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,3,0,0.00,0.6336,3.0390,1.114,22.39,211.65,1.65,142.75,...,16.878272,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,4,0,0.00,0.9671,17.8300,0.586,162.26,58.42,111.33,38.38,...,70.558701,0.000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22489,22489,0,25.30,0.4371,0.7163,0.403,4.01,281.52,14.50,146.17,...,9.354590,25.316,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
22490,22490,0,24.12,0.0586,0.9867,0.929,12.83,109.95,177.76,192.72,...,7.331688,24.360,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
22491,22491,0,24.59,0.6969,2.4530,0.743,13.68,96.50,295.24,11.94,...,18.525280,24.546,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
22492,22492,0,25.01,0.1730,0.8573,0.709,3.92,302.94,333.90,189.79,...,5.827525,25.138,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
22493,22493,0,22.86,0.4106,1.3280,0.783,12.85,93.56,292.47,36.40,...,12.672005,22.811,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0